"""
Django settings for assignment project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'qum7%49y0f%%=6m=mruy6d@*1*8#1*ec8ovx)llf-86flc0#kq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get('DEBUG', 0)))

APPEND_SLASH=True

ALLOWED_HOSTS = [ "localhost" ]
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS')
if ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS.extend(ALLOWED_HOSTS_ENV.split(','))


# Application definition

ROOT_URLCONF = 'assignment.urls'

WSGI_APPLICATION = 'assignment.wsgi.application'

